import { existsSync } from "node:fs";
import { homedir } from "node:os";
import { TUNING } from "#shared/tuning";

export function expandHome(p: string): string {
  return p.startsWith("~") ? homedir() + p.slice(1) : p;
}

// Per-machine overrides. The service files are regenerated by every install and
// deploy, so this is the only place a personal setting survives. A real env var
// still wins: loadEnvFile never overwrites what is already set.
const envFile = expandHome(TUNING.ENV_FILE);
if (existsSync(envFile)) process.loadEnvFile(envFile);

export const config = {
  port: Number(process.env.REV_PORT ?? TUNING.PORT),
  host: process.env.REV_HOST ?? TUNING.HOST,
  roots: (process.env.REV_ROOTS?.split(":") ?? TUNING.DEFAULT_ROOTS).map(expandHome),
  depth: Number(process.env.REV_DEPTH ?? TUNING.DISCOVERY_MAX_DEPTH),
  dbPath: expandHome(process.env.REV_DB ?? TUNING.DB_PATH),
  personalHosts: process.env.REV_PERSONAL_HOSTS?.split(",").map((h) => h.trim()).filter(Boolean)
    ?? [...TUNING.PERSONAL_HOSTS],
  personalOwners: process.env.REV_PERSONAL_OWNERS?.split(",").map((o) => o.trim().toLowerCase()).filter(Boolean)
    ?? [...TUNING.PERSONAL_OWNERS],
};
